# Generated by Django 5.0.6 on 2024-06-16 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuserdetails',
            name='location',
        ),
        migrations.AddField(
            model_name='customuserdetails',
            name='closing_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuserdetails',
            name='opening_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
