# Generated by Django 5.0.6 on 2024-06-20 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_customuserdetails_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254)),
                ('user_name', models.CharField(max_length=100)),
                ('booking_time', models.DateTimeField()),
                ('service', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='customuserdetails',
            name='service_name',
            field=models.CharField(default='Default Service', max_length=100),
        ),
        migrations.AddField(
            model_name='customuserdetails',
            name='bookings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_bookings', to='app.booking'),
        ),
    ]
