# Generated by Django 5.0.3 on 2024-08-12 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_booking_customuserdetails_service_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.customuserdetails'),
        ),
    ]
