# Generated by Django 5.0.6 on 2024-08-13 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_customusermodel_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuserdetails',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuserdetails',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
