# Generated by Django 5.0.6 on 2024-08-13 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_customuserdetails_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuserdetails',
            name='map_photo',
            field=models.ImageField(blank=True, null=True, upload_to='location_photos/'),
        ),
        migrations.AddField(
            model_name='customuserdetails',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='services_photos/'),
        ),
    ]
